### ISSUE TITLE
Revert Email Check

### ISSUE THREAD

**Issue by mhils** [avatsaev/slackin#1]
Hi,

Thanks for your work on adding recaptcha support to slackin! This was really handy for signing up our Google Summer of Code Students this year. After using it for a few hundred signups, I'd like to suggest that b5d415fc2f91f9b199566ae33205780288ab2671 should be reverted and/or replaced with something better. The ReCaptcha implementation is great, but the email validation is problematic:

1. First, the error condition for invalid emails is wrong: [index.js#L242](https://github.com/avatsaev/slackin/blob/b5d415fc2f91f9b199566ae33205780288ab2671/dist/index.js#L242) should not return 200 OK.
2. Second, and more importantly, `email-check` returns `false` for a whole bunch of working emails on our DigitalOcean instance (this is how we actually discovered the first issue). Email validation will never be perfect, so in the interest of robustness I'd suggest a simple `email.indexOf("@") > -1` instead.

Thanks again!

Max

---
refs https://github.com/rauchg/slackin/pull/234

**Comment by avatsaev** [comment]
Thanks for the feed back, I'll try to look into it when I have time, or you can send a PR and I'll review and merge it.

**Comment by chadwhitacre** [comment]
I think #2 closes this, ya?

**Comment by avatsaev** [comment]
Yes, closing.
